#!/bin/bash

g++ -O2 ./src/Composition.cpp ./src/GeneticAlgorithm.cpp ./src/Sound.cpp ./src/Beat.cpp ./src/Bar.cpp ./src/Music.cpp ./src/SoundIO.cpp ./src/IOfunction.cpp ./src/main.cpp -o ./handler/main
