#!/bin/bash

./compileTest
./algoTest

./handler/pypy/bin/pypy -O ./handler/generatewave1.py
./handler/pypy/bin/pypy -O ./handler/generatewave2.py
./handler/pypy/bin/pypy -O ./handler/generatewave3.py
./handler/pypy/bin/pypy -O ./handler/generatewave4.py

python2 -O ./handler/combine.py

rm 1.wav 2.wav 3.wav 4.wav ./handler/generatewave*
