#!/bin/bash

echo "====== Compile phase ====== "
echo "Compiling ... "
./compileTest
echo "Compiling ...OK! "
./algoTest
echo "====== Runing phase====== "
echo "Runing ... "
echo "Generateing ... "
./handler/pypy/bin/pypy -O ./handler/generatewave1.py
./handler/pypy/bin/pypy -O ./handler/generatewave2.py
./handler/pypy/bin/pypy -O ./handler/generatewave3.py
./handler/pypy/bin/pypy -O ./handler/generatewave4.py
echo "Synthesizing ... "
python2 -O ./handler/combine.py
echo "OK!"
echo "======= Cleaning ======"
rm 1.wav 2.wav 3.wav 4.wav ./handler/generatewave* ./handler/main
echo "Done!"
